### PR TITLE
Add device ID for Adaprox Fingerbot (y6kttvd6)

### PR DESCRIPTION
**Pull request by daveyijzermans**
Just a small bit of copy-paste work really to support the Adaprox branded Fingerbot (non-plus) as well.

### CODE REVIEW

**Comment by PlusPlus-ua** [comment]
Update please README.md as well.

**Comment by daveyijzermans** [comment]
Split it into Fingerbot and Adaprox Fingerbot because the Adaprox has a built-in battery unlike the Tuya one that uses a CR2. Is that okay?

**Comment by PlusPlus-ua** [comment]
Yes, thank you.

**Comment by PlusPlus-ua** [comment]
One more question. Since your device has the built-in battery, has it a datapoint for charging state? Could you please check it?  Here is an instruction how to obtain datapoint ids for Tuya devices: https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html#_9-find-your-data-point

**Comment by daveyijzermans** [comment]
> One more question. Since your device has the built-in battery, has it a datapoint for charging state? Could you please check it? Here is an instruction how to obtain datapoint ids for Tuya devices: https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html#_9-find-your-data-point

Sorry for the delay, but I could not my Tuya devices to show up in their dashboard and retrieve the DP IDs for you.

Scherm­afbeelding 2023-05-05 om 21 17 40

I even tried creating a new account and adding the Fingerbot with and without Bluetooth bridges, but I could not get the devices to show. I also have a project in the IoT dashboard for Home Assistant, but that also shows zero devices, even though they do load in Home Asssistant. I also tried tuya-cli but it couldn't connect to Bluetooth child devices (using a bluetooth bridge)

Sorry!

**Pull request merged**
