### PR TITLE
Added Entrance Smart lock (isk2p555) + Updated some translations

### PR DESCRIPTION
**Pull request by drewpo28**
Added Entrance Smart lock (isk2p555) + Updated some translations
@PlusPlus-ua, please review.

### CODE REVIEW

**Comment by PlusPlus-ua** [comment]
Hi, thank you for your contribution. One thing, you have to change strings.json file and then changes will be distributed to translations/en.json by the python script "python -m script.translations develop --integration tuya_ble", fix it please.

**Comment by drewpo28** [comment]
@PlusPlus-ua , thank you for the comment. I have fixed strings.json file.

**Comment by patrickbard** [comment]
I was literally doing the same thing last week to support my smart lock (same product id), I just didn't had enough time to test it well.

I'm glad you did it @drewpo28, maybe I'll check Tuya IOT platform to see what new features I could help implement.

One thing strange that happened to me was that `lock_motor_state` was not working properly, it tries to change the state and send the correct packages, but state doesn't change.

**Comment by drewpo28** [comment]
@patrickbard, thank you. It will be great if you able to add some new features.
The `lock_motor_state` don't work for me in Tuya Smart also. :(

**Comment by leonardoleb** [comment]
Firstly, thank you for your code @drewpo28, it was a great help to me.

I'm trying to add my smart lock as well (product id: uamrw6h3).

Could you clarify the purpose of lock_motor_state? In the case of my device, it seems to only report whether the lock is closed or open.

**Comment by Noords89** [comment]
I'm in the same boat as @leonardoleb , i've added my locks product ID and the integration now recognises the lock and 5 entites however all show as unavailable. Product ID is omdezogp.
I've been able to send limited instructions to the lock from within the Tuya API explorer (i.e. change volume) but haven't had any luck unlocking the door from either HA or Tuya. Any asssitance from @drewpo28 would be greatly appreciated.

**Pull request merged**
