### PR TITLE
Add new Lock category (jtmspro), device(Raykube K7 Pro+ id xicdxood) and functions, includes ble unlock

### PR DESCRIPTION
**Pull request by raphaeleduardo42**
New **Device:**

* Raykube K7 Pro+

New **features:**

* Working Unlock
* Sensor based last used unlock method
* Language change

Not implemented:

- [ ] Doorbell
- [ ] Creating/Deleting unlock options
- [ ] Motor state

I was able to almost fully deliver all base functions from the lock, including ble unlock.

My idea on having a `Last used `sensor is to identify how opened the lock and when, the data point info is delivered to the sensor but if it's the same from before it doesn't update (maybe you could look at this behavior @PlusPlus-ua?).

The `lock_motor_state` showed very unstable on my tests, so I decided to not implement it yet. From what I gather, it show if the lock itself is or isn't locked, based on the motor, but don't control the device which I found to by controlled by `ble_unlock_check` DP.

For future further development of this device and others, mine results extract from Tuya IOT are showed bellow.

Thanks in advance from the maintenance of the repository.
Greetings from Brazil.

```
{
	"result": {
	  "category": "jtmspro",
	  "functions": [
		{
		  "code": "unlock_method_create",
		  "desc": "{}",
		  "name": "添加开门方式",
		  "type": "Raw",
		  "values": "{}"
		},
		{
		  "code": "unlock_method_delete",
		  "desc": "{}",
		  "name": "删除开门方式",
		  "type": "Raw",
		  "values": "{}"
		},
		{
		  "code": "unlock_method_modify",
		  "desc": "{}",
		  "name": "修改开门方式",
		  "type": "Raw",
		  "values": "{}"
		},
		{
		  "code": "language",
		  "desc": "{\"range\":[\"chinese_simplified\",\"english\"]}",
		  "name": "门锁语言切换",
		  "type": "Enum",
		  "values": "{\"range\":[\"chinese_simplified\",\"english\"]}"
		},
		{
		  "code": "beep_volume",
		  "desc": "{\"range\":[\"mute\",\"low\",\"normal\",\"high\"]}",
		  "name": "门锁本地导航音量",
		  "type": "Enum",
		  "values": "{\"range\":[\"mute\",\"low\",\"normal\",\"high\"]}"
		},
		{
		  "code": "rtc_lock",
		  "desc": "{}",
		  "name": "硬件时钟RTC",
		  "type": "Boolean",
		  "values": "{}"
		},
		{
		  "code": "synch_method",
		  "desc": "{}",
		  "name": "同步开门方式（全量同步）",
		  "type": "Raw",
		  "values": "{}"
		},
		{
		  "code": "check_code_set",
		  "desc": "{}",
		  "name": "配置蓝牙解锁校验码",
		  "type": "Raw",
		  "values": "{}"
		},
		{
		  "code": "ble_unlock_check",
		  "desc": "{}",
		  "name": "蓝牙解锁（带校验码）",
		  "type": "Raw",
		  "values": "{}"
		}
	  ],
	  "status": [
		{
		  "code": "unlock_method_create",
		  "name": "添加开门方式",
		  "type": "Raw",
		  "values": "{}"
		},
		{
		  "code": "unlock_method_delete",
		  "name": "删除开门方式",
		  "type": "Raw",
		  "values": "{}"
		},
		{
		  "code": "unlock_method_modify",
		  "name": "修改开门方式",
		  "type": "Raw",
		  "values": "{}"
		},
		{
		  "code": "residual_electricity",
		  "name": "剩余电量",
		  "type": "Integer",
		  "values": "{\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
		},
		{
		  "code": "unlock_fingerprint",
		  "name": "指纹解锁",
		  "type": "Integer",
		  "values": "{\"min\":0,\"max\":999,\"scale\":0,\"step\":1}"
		},
		{
		  "code": "unlock_password",
		  "name": "普通密码解锁",
		  "type": "Integer",
		  "values": "{\"min\":0,\"max\":999,\"scale\":0,\"step\":1}"
		},
		{
		  "code": "unlock_dynamic",
		  "name": "动态密码解锁",
		  "type": "Integer",
		  "values": "{\"min\":0,\"max\":999,\"scale\":0,\"step\":1}"
		},
		{
		  "code": "unlock_card",
		  "name": "卡片解锁",
		  "type": "Integer",
		  "values": "{\"min\":0,\"max\":999,\"scale\":0,\"step\":1}"
		},
		{
		  "code": "unlock_ble",
		  "name": "蓝牙解锁记录",
		  "type": "Integer",
		  "values": "{\"min\":0,\"max\":999,\"scale\":0,\"step\":1}"
		},
		{
		  "code": "alarm_lock",
		  "name": "告警",
		  "type": "Enum",
		  "values": "{\"range\":[\"wrong_finger\",\"wrong_password\",\"wrong_card\",\"wrong_face\",\"tongue_bad\",\"too_hot\",\"unclosed_time\",\"tongue_not_out\",\"pry\",\"key_in\",\"low_battery\",\"power_off\",\"shock\",\"defense\"]}"
		},
		{
		  "code": "doorbell",
		  "name": "门铃呼叫",
		  "type": "Boolean",
		  "values": "{}"
		},
		{
		  "code": "language",
		  "name": "门锁语言切换",
		  "type": "Enum",
		  "values": "{\"range\":[\"chinese_simplified\",\"english\"]}"
		},
		{
		  "code": "beep_volume",
		  "name": "门锁本地导航音量",
		  "type": "Enum",
		  "values": "{\"range\":[\"mute\",\"low\",\"normal\",\"high\"]}"
		},
		{
		  "code": "rtc_lock",
		  "name": "硬件时钟RTC",
		  "type": "Boolean",
		  "values": "{}"
		},
		{
		  "code": "synch_method",
		  "name": "同步开门方式（全量同步）",
		  "type": "Raw",
		  "values": "{}"
		},
		{
		  "code": "check_code_set",
		  "name": "配置蓝牙解锁校验码",
		  "type": "Raw",
		  "values": "{}"
		},
		{
		  "code": "ble_unlock_check",
		  "name": "蓝牙解锁（带校验码）",
		  "type": "Raw",
		  "values": "{}"
		}
	  ]
	},
	"success": true,
	"t": 1691113353718,
	"tid": "2eb5a0f0326811ee804ade073cb82c5d"
  }
```

### CODE REVIEW

**Comment by leonardoleb** [comment]
Nice work, @raphaeleduardo42 !

I'm sure this will greatly help in supporting other smart locks. I've seen many people requesting the addition of new devices in the 'jtmspro' category. It seems that the DpIds are similar to yours.

**Comment by homecb** [comment]
Thanks for your work @raphaeleduardo42 ! Hopefully the PR gets approved very soon.

**Comment by homecb** [comment]
@raphaeleduardo42 I'm trying to test your branch I've the same device but when adding the integration I get the following message:

"No unconfigured devices found."

Any ideas?

**Comment by raphaeleduardo42** [comment]
> @raphaeleduardo42 I'm trying to test your branch I've the same device but when adding the integration I get the following message:
> 
> 
> 
> "No unconfigured devices found."
> 
> 
> 
> Any ideas?

This is happens when your server can't see the lock BLE advertisement. Often happens when your Bluetooth isn't strong enough or the lock is connected with another device.

Try disconnect it from your phone/tablet/hub. If no success bring your server closer, use a stronger dongle or build a Esp32 BT gateway.

**Comment by bb12489** [comment]
@raphaeleduardo42 I too tried testing your branch, but it doesn't look like it exposes anything for my lock. Mine is slightly different than the lock you have, but I saw that your device category is jtmspro, same as mine. My device id is kholoaew. I submitted an issue to add support for this on @PlusPlus-ua repo.

**Comment by bb12489** [comment]
@raphaeleduardo42 I used your PR as a guide to add support for my lock. It's the Nice Digi X1. So far it looks like everything is working sensor-wise. However the unlock button doesn't appear to do anything. I checked the device properties in the API explorer on Tuya's IOT site, and my ble_unlock_check has the same ID of 71 as yours does. Is there anything I may be missing to get the actual unlock to work?

**Comment by asdfghjkai** [comment]
> @raphaeleduardo42 I used your PR as a guide to add support for my lock. It's the Nice Digi X1. So far it looks like everything is working sensor-wise. However the unlock button doesn't appear to do anything. I checked the device properties in the API explorer on Tuya's IOT site, and my ble_unlock_check has the same ID of 71 as yours does. Is there anything I may be missing to get the actual unlock to work?

Interested here also. I've got a BluSafe Origin Smart, which exposes the DP71 for ble unlock. I'm surprised if it's working without key, I'm looking through docs to try and setup the process for defining a new key, then passing through. Will share if I get anywhere anytime soon, but don't hold out hope.

Following DPs exposed:
{"1":"Add unlock method","2":"Delete unlock method","3":"Modify unlock method","8":"Remaining battery","11":"Deadlocked","12":"fingerprint unlock","15":"card unlock","19":"Ble unlock record","21":"lock alarm","22":"Duress Alarm","31":"Lock Volume","44":"rtc lock","54":"Synchronous full unlock method","61":"Code-free remote unlock","62":"Remote unlock","63":"Remote voice unlock","69":"get record","70":"Set check code","71":"Ble unlock (with key)","72":"Unlock/lock record (with key)","73":"set remote check code","101":"Siri unlock"}

**Comment by doli11** [comment]
@raphaeleduardo42 thank you very much for your efforts, I bought a bunch of smart locks to see if I can get one integrated into HA. I also bought a gateway (BLE/Zigbee/Wifi) to be able to perform tests within tuya iot cloud and built a bluetooth proxy. After several hours without any success (tuya ble integration exposed one of them with only one entity (signal strenght)) I came across your tests and modified your files to match one lock.
It's a "S1-TY-BLE-PRO" (product id: xqeob8h6) which is sold rebranded by a lot of chinese companies. A lot of the entities are working (alarm, last used card/fingerprint, signal strenght, motor state, battery) but the important one "unlock" is not working. I've tried DP71 and the lock is doing "something" if I press the button because I can hear the motor working but it is not unlocking. I've also tried some other datapoints which sounded like they could do the job without success. As you have yours running... do you have any ideas what else I can try? Below my device details and the extraction of DPs 

Thank you in advance :)



```
 {
  "result": {
    "active_time": 1703203765,
    "category": "jtmspro",
    "create_time": 1703003068,
    "custom_name": "",
    "icon": "smart/icon/ay15637661355438qua2/f63a35cd47c91c90c5369b8bd0afacbc.png",
    "id": "xxx",
    "ip": "",
    "is_online": true,
    "lat": "xxx",
    "local_key": "xxx",
    "lon": "xxx",
    "model": "S1",
    "name": "S1-TY-BLE-PRO",
    "product_id": "xqeob8h6",
    "product_name": "S1-TY-BLE-PRO",
    "sub": true,
    "time_zone": "+01:00",
    "update_time": 1703203765,
    "uuid": "uuid1c469a584f0c"
  },
  "success": true,
  "t": 1703208685099,
  "tid": "d2057789a06911ee84c63652eadeec7d"
 }
```

 ```
{
  "result": {
    "properties": [
      {
        "code": "unlock_method_create",
        "custom_name": "",
        "dp_id": 1,
        "time": 1703211599000,
        "value": "A/8BAQEAAA=="
      },
      {
        "code": "unlock_method_delete",
        "custom_name": "",
        "dp_id": 2,
        "time": 1703209090780
      },
      {
        "code": "unlock_method_modify",
        "custom_name": "",
        "dp_id": 3,
        "time": 1703209090780
      },
      {
        "code": "residual_electricity",
        "custom_name": "",
        "dp_id": 8,
        "time": 1703211569000,
        "value": 100
      },
      {
        "code": "unlock_fingerprint",
        "custom_name": "",
        "dp_id": 12,
        "time": 1703203765342,
        "value": 0
      },
      {
        "code": "unlock_card",
        "custom_name": "",
        "dp_id": 15,
        "time": 1703203765342,
        "value": 0
      },
      {
        "code": "unlock_key",
        "custom_name": "",
        "dp_id": 16,
        "time": 1703203765342,
        "value": 0
      },
      {
        "code": "unlock_ble",
        "custom_name": "",
        "dp_id": 19,
        "time": 1703203765342,
        "value": 0
      },
      {
        "code": "lock_record",
        "custom_name": "",
        "dp_id": 20,
        "time": 1703209090780
      },
      {
        "code": "alarm_lock",
        "custom_name": "",
        "dp_id": 21,
        "time": 1703210871000,
        "value": "wrong_finger"
      },
      {
        "code": "hijack",
        "custom_name": "",
        "dp_id": 22,
        "time": 1703203765342,
        "value": false
      },
      {
        "code": "doorbell",
        "custom_name": "",
        "dp_id": 24,
        "time": 1703203765342,
        "value": false
      },
      {
        "code": "message",
        "custom_name": "",
        "dp_id": 25,
        "time": 1703203765342,
        "value": false
      },
      {
        "code": "automatic_lock",
        "custom_name": "",
        "dp_id": 33,
        "time": 1703211569000,
        "value": true
      },
      {
        "code": "unlock_switch",
        "custom_name": "",
        "dp_id": 34,
        "time": 1703211569000,
        "value": "single_unlock"
      },
      {
        "code": "auto_lock_time",
        "custom_name": "",
        "dp_id": 36,
        "time": 1703211569000,
        "value": 5
      },
      {
        "code": "closed_opened",
        "custom_name": "",
        "dp_id": 40,
        "time": 1703203765342,
        "value": "unknown"
      },
      {
        "code": "rtc_lock",
        "custom_name": "",
        "dp_id": 44,
        "time": 1703203765342,
        "value": false
      },
      {
        "code": "manual_lock",
        "custom_name": "",
        "dp_id": 46,
        "time": 1703206555987,
        "value": false
      },
      {
        "code": "lock_motor_state",
        "custom_name": "",
        "dp_id": 47,
        "time": 1703211569000,
        "value": false
      },
      {
        "code": "synch_method",
        "custom_name": "",
        "dp_id": 54,
        "time": 1703211578000,
        "value": "AQA="
      },
      {
        "code": "remote_no_dp_key",
        "custom_name": "",
        "dp_id": 61,
        "time": 1703206563135,
        "value": "AAAB"
      },
      {
        "code": "unlock_phone_remote",
        "custom_name": "",
        "dp_id": 62,
        "time": 1703206563000,
        "value": 1
      },
      {
        "code": "unlock_voice_remote",
        "custom_name": "",
        "dp_id": 63,
        "time": 1703203765342,
        "value": 0
      },
      {
        "code": "record",
        "custom_name": "",
        "dp_id": 69,
        "time": 1703211569000,
        "value": "AAEB"
      },
      {
        "code": "check_code_set",
        "custom_name": "",
        "dp_id": 70,
        "time": 1703209124000,
        "value": "AAH//wAAAAAAAAAAAP//AA=="
      },
      {
        "code": "ble_unlock_check",
        "custom_name": "",
        "dp_id": 71,
        "time": 1703209090780
      },
      {
        "code": "unlock_record_check",
        "custom_name": "",
        "dp_id": 72,
        "time": 1703209090780
      },
      {
        "code": "remote_pd_setkey_check",
        "custom_name": "",
        "dp_id": 73,
        "time": 1703203769434,
        "value": "AAH//zUyOTcwNDc1AQABAA=="
      },
      {
        "code": "unlock_double_kit",
        "custom_name": "",
        "dp_id": 74,
        "time": 1703209090780
      },
      {
        "code": "unlock_ble_ibeacon",
        "custom_name": "",
        "dp_id": 86,
        "time": 1703203765342,
        "value": 0
      },
      {
        "code": "ibeacon_scan_mode",
        "custom_name": "",
        "dp_id": 87,
        "time": 1703203765342,
        "value": "always"
      },
      {
        "code": "rssi_sensitivity_level",
        "custom_name": "",
        "dp_id": 88,
        "time": 1703203765342,
        "value": "inactive"
      },
      {
        "code": "ibeacon_switch",
        "custom_name": "",
        "dp_id": 90,
        "time": 1703211569000,
        "value": false
      }
    ]
  },
  "success": true,
  "t": 1703347060632,
  "tid": "00420beea1ac11ee9384da1e0a435480"
}
```

**Comment by boyfromgermany** [comment]
I Tested this with my Lockin G30(3oe761xu) wich also is jtmspro and has similar codes, however the unlock function is not working 

`
2024-02-07 20:25:09.734 DEBUG (MainThread) [custom_components.tuya_ble.cloud] Retrieved: uuid: xxxxxxxxxxxxxxxx, local_key: xxxxxxxxxxxxxxxx, device_id: xxxxxxxxxxxxxxxx, category: jtmspro, product_id: 3oe761xu, device_name: G30 Smart Lock-EU, product_model: EU, product_name: G30 Smart Lock-EU
`

`"8":"Remaining Battery",
"16":"Unlock with Manual",
"19":"Bluetooth Unlock",
"20":"Lock Records",
"21":"Lock Alerts",
"31":"Door lock tone volume",
"33":"Auto Lock",
"36":"Auto Lock Delay",
"40":"door opening and closing state",
"44":"Local RTC",
"46":"Manual Lock",
"47":"Lock Status",
"54":"Sync Access Method",
"59":"Calibration",
"61":"No-Code Unlock (with Key)",
"62":"Remote Phone Unlock",
"63":"Remote Voice Unlock",
"68":"Alarm unlocked door",
"69":"Get Records",
"70":"Configure Verification Code",
"71":"Bluetooth Unlock (with Verification Codes)",
"72":"Unlock/Lock Records (with Verification Codes)",
"73":"Set Remote Unlock (with Verification Codes)",
"82":"Alert Volume",
"83":"Ringtone",
"85":"Alert",
"91":"Fault",
"110":"Boot page delivery",
"118":"Calibrate unlock point",
"119":"Calibrate lock point",
"120":"Lock angle report",
"121":"Unlock angle report",
"122":"Calibration CCW",
"123":"Calibration reference zero",
"124":"Electric current",
"125":"Voltage"}`

`
    "G30 Smart Lock-EU": {
        "id": "bfbe0ayfhrly4tbh",
        "local_key": "kj+).1$<bm%fBIp#",
        "category": "jtmspro",
        "uuid": "602b3f9b7433fa44",
        "product_id": "3oe761xu",
        "dps": {
            "16": 0,
            "19": 0,
            "21": "key_in",
            "31": "high",
            "33": false,
            "36": 0,
            "40": "unknown",
            "44": false,
            "46": true,
            "47": false,
            "62": 0,
            "63": 0,
            "68": "function1",
            "69": "//8AATU5OTk4NTg1AA==",
            "70": "AAH//wAAAAAAAAAAAP//AA==",
            "71": "AAH//zU5OTk4NTg1AWXDyqkAAQ==",
            "73": "AAH//zU5OTk4NTg1AQABAA==",
            "8": 90,
            "82": "mute",
            "83": "ringtone_0",
            "85": false,
            "91": 0
            "110": "4QA=",
            "118": 0,
            "119": 0,
            "120": 0,
            "121": 0,
            "122": 0,
            "123": 0,
            "124": 0,
            "125": 5673,
        }
    }
}
`

**Comment by pathob** [comment]
@raphaeleduardo42 May I ask why you closed this (respectively why you deleted the head repo)?

**Pull request closed without merging**
