### PR TITLE
fix: Compatibility with HA 2024.1 - import consts from core

### LINKED ISSUE #94: 2024.1 give problems.
I updated to the beta release of: [2024.1](https://rc--home-assistant-docs.netlify.app/blog/2023/12/27/release-20241/) 2024.1
after that the following error occurred.

Setup failed for custom integration 'tuya_ble': Unable to import component: cannot import name 'CONF_COUNTRY_CODE' from 'homeassistant.components.tuya.const' (/usr/src/homeassistant/homeassistant/components/tuya/const.py)

### LINKED ISSUE #98: Error after HA update to: 2024.1.0
Hi After update to version 2024.1.0 integration stopped working. Trying to add another instance then displays:

`Error
Config flow could not be loaded: {"message":"Invalid handler specified"`

logs:

Logger: homeassistant.config_entries
Source: config_entries.py:2087
First occurred: 16:27:32 (5 occurrences)
Last logged: 16:40:57

Error occurred loading flow for integration tuya_ble: cannot import name 'CONF_COUNTRY_CODE' from 'homeassistant.components.tuya.const' `(/usr/src/homeassistant/homeassistant/components/tuya/const.py)

Core
2024.1.0
Supervisor
2023.12.0
Operating System
Frontend
20240103.3

### PR DESCRIPTION
**Pull request by michalbundyra**
Fixes #94
Fixes #98 

Import consts from homeassistant.core

See:
- https://github.com/home-assistant/core/pull/105657
- https://github.com/home-assistant/core/pull/105640

### CODE REVIEW

**Comment by mclever** [comment]
Thank you @michalbundyra!

**Comment by Bilalline** [comment]
Ошибка
Не удалось загрузить мастер настройки: {"message":"Invalid handler specified"}

**Comment by homecb** [comment]
Unfortunately, it looks like none of the open PR's will be merged anytime soon, or at all.

**Comment by donparlor** [comment]
I'm also waiting for those PR to be merged...

**Pull request closed without merging**
